"common.error" = "Error";
"common.ok" = "OK";
"common.delete" = "Delete";
"common.cancel" = "Cancel";

"error_message.unexpected_error" = "Unexpected error occurred";
"error_message.disconnected" = "Network disconnected";
"error_message.log_unavailable" = "Log of this workflow is currently unavailable";
"error_message.sign_out_failed" = "Sign out unexpectedly failed. Please revoke OAuth token from github settings instead. Sorry!";

"sign_in_feature.sign_in_with_github" = "Sign In with GitHub";

"actions_feature.title.repository_list" = "Repositories";

"actions_feature.message.workflow_request_sent" = "%@ request successfully sent";
"actions_feature.message.in_progress_log_unavailable" = "Log is unavailable while the workflow is in progress";

"actions_feature.workflow_run_list.empty_message" = "No workflow runs";

"settings_feature.sign_out_from_github" = "Sign Out";
